Fixed python version 3.5 to 3.4
Dockerfile FROM python 3.5 can't build hubblemon docker images

Error :
 AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
 INFO[0001] The command [/bin/sh -c python manage.py migrate] returned a non-zero code: 1

HTMLParse Error is deprecated from python 3.3 onwards and removed in python 3.5

Degrading python version from 3.5 to 3.4 can fix this probelm.